### ISSUE TITLE
use yolox

### ISSUE THREAD

**Issue by fanfanfan111** [shyhyawJou/EigenCAM-Pytorch#1]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/104192127/200570905-47290522-4dea-4914-b9a1-551ed3bf8cf4.png">

**Comment by shyhyawJou** [comment]
> <img alt="image" width="459" src="https://user-images.githubusercontent.com/104192127/200570905-47290522-4dea-4914-b9a1-551ed3bf8cf4.png">

It seems that your variable "model" is a dictionary.
Please let "model" be a "nn.Module" object.
Though I never use YOLOX, but i guess the model path you specify is a weight-only .pt file.
You should specify a .pt file inclusive of weight and model architecture. You can refer to README

**Comment by fanfanfan111** [comment]
> > <img alt="图片" width="459" src="https://user-images.githubusercontent.com/104192127/200570905-47290522-4dea-4914-b9a1-551ed3bf8cf4.png">
> 
> 看来您的变量“模型”是一本字典。 请让“模型”成为“nn.Module”对象。 虽然我从不使用 YOLOX，但我猜你指定的模型路径是一个仅权重的 .pt 文件。 您应该指定一个包含权重和模型架构的 .pt 文件。你可以参考README

您说的很对 我打印了模型文件发现只打印了权重，没有模型，请问如何读取包含权重和模型的文件？

**Comment by shyhyawJou** [comment]
> > > <img alt="图片" width="459" src="https://user-images.githubusercontent.com/104192127/200570905-47290522-4dea-4914-b9a1-551ed3bf8cf4.png">
> > 
> > 
> > 看来您的变量“模型”是一本字典。 请让“模型”成为“nn.Module”对象。 虽然我从不使用 YOLOX，但我猜定的模型路径是一个仅权重的 .pt 文件。 您应该指定一个包含权重和模型架构的 .pt 文件。你可以参考README> 
> 您说的很对 我打印了模型文件发现只打印了权重，没有模型，请问如何读取包含权重和模型的文件？
兩種方法:

現在你應該要想辦法得到一個包含權重和模型結構的 YOLOX .pt 檔，這個你只能去修改一下 YOLOX 的程式碼:
先利用 YOLOX 的程式把你訓練好的模型載入， 然後添加這行 `torch.save(model, 路徑)` ，這樣你就會存下包含權重和結構的 .pt，然後你再用我在 README 寫的指令，這樣應該就可以了

**Comment by fanfanfan111** [comment]
> 
好的好的 十分感激！

**Comment by shyhyawJou** [comment]
@fanfanfan111 
您好，請問您的問題解決了嗎? 如果解決了，我就把 issue 關掉了喔

**Comment by fanfanfan111** [comment]
> @fanfanfan111 您好，請問您的問題解決了嗎? 如果解決了，我就把 issue 關掉了喔

好的好的 谢谢了
